# -*- coding: utf-8 -*-
"""Uber_EDA_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dks9N01PzO0ksUs8ulocBsRjejfXhI7l

# Uber Supply-Demand Gap - Exploratory Data Analysis (EDA)
Using Pandas, Matplotlib, and Seaborn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# For cleaner visuals
sns.set(style="whitegrid")

from google.colab import files
uploaded = files.upload()

# Load the dataset
df = pd.read_csv("uber_data.csv")

# Display first 5 rows
df.head()

# Shape of data
print("Shape:", df.shape)

# Info
df.info()

# Describe numeric data
df.describe()

# Missing values per column
df.isnull().sum()

# Count duplicate rows
df.duplicated().sum()

# Convert to datetime
df['Request Timestamp'] = pd.to_datetime(df['Request Timestamp'])
df['Drop TImestamp'] = pd.to_datetime(df['Drop TImestamp'])

# Extract Hour and Date
df['Hour'] = df['Request Timestamp'].dt.hour
df['Date'] = df['Request Timestamp'].dt.date

df[['Request Timestamp', 'Hour', 'Date']].head()

# Status distribution
print(df['Status'].value_counts())

# Pickup point distribution
print(df['Pickup point'].value_counts())

# Group by Hour and Status
df.groupby('Hour')['Status'].value_counts()

"""## Visualizations"""

plt.figure(figsize=(8,5))
sns.countplot(x='Status', data=df)
plt.title("Overall Status Distribution")
plt.show()

plt.figure(figsize=(10,6))
df['Hour'].value_counts().sort_index().plot(kind='line', marker='o')
plt.title("Hourly Request Volume")
plt.xlabel("Hour")
plt.ylabel("Requests")
plt.grid(True)
plt.show()

unfulfilled = df[df['Status'] != 'Trip Completed']

plt.figure(figsize=(10,6))
sns.countplot(x='Hour', hue='Pickup point', data=unfulfilled)
plt.title("Unfulfilled Requests by Hour and Pickup Point")
plt.xlabel("Hour")
plt.ylabel("Unfulfilled Requests")
plt.show()

cancelled = df[df['Status'] == 'Cancelled']

plt.figure(figsize=(10,6))
sns.countplot(x='Hour', data=cancelled, color='red')
plt.title("Cancelled Requests by Hour")
plt.xlabel("Hour")
plt.ylabel("Cancelled Requests")
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x='Pickup point', hue='Status', data=df)
plt.title("Status Distribution by Pickup Point")
plt.xlabel("Pickup Point")
plt.ylabel("Number of Requests")
plt.legend(title="Status")
plt.show()